Dev
Cource-startup/app_front pull request #2
Opened 2024-06-11 18:34 UTC by TimaliveProgman

2024-06-11 18:35 UTC, TimaliveProgman commented
send data with riverpod

2024-06-12 03:17 UTC, denis-progman reviewed
somehow I don't see all the changes connected with the provider usage. 
So I cannot check all of your work. we need to discuss it at least in the TG chat.

2024-06-12 03:17 UTC, denis-progman commented on output.txt
What is this? do we really need this file?

2024-06-12 03:17 UTC, denis-progman commented on lib/providers/auth_providers.dart
>      final isCleared = await prefs.clear();
prefs - is an unclear variable name. let's don't cut down words. the same thing about the name of the provider. 
Please rename it completely understandable and logicaly.

2024-06-15 02:09 UTC, denis-progman requested changes
Please fix all of the comments and comment back.

2024-06-16 12:59 UTC, TimaliveProgman commented on output.txt
i don't khow, I see it for the first time

2024-06-19 08:14 UTC, TimaliveProgman commented on output.txt
file deleted

2024-06-19 08:15 UTC, TimaliveProgman commented on lib/providers/auth_providers.dart
>      final isCleared = await prefs.clear();
changed

2024-07-03 05:48 UTC, denis-progman approved these changes

2024-07-03 05:49 UTC, merged